<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Create New Game</title>

    <!-- Bootstrap core CSS -->
    <link href="./css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="./css/signin.css" rel="stylesheet">
</head>

<body>

<div class="container">

    <form class="form-signin" id="createGame" action="createGame.php" method="POST">
        <div class="form-group">
            <label for="gameName">What is the name of the game? </label>
            <input  class="form-control" id="gameName" name = "gameName" aria-describedby="emailHelp" placeholder="friends, family, etc...">

        </div>

        <div class="form-group">
            <label for="playerSelect">What players do you want?( you can pick more than one)</label>
            <select name="playerSelect[]" multiple class="form-control" id="playerSelect" tabindex="1">

            <?php
            include "Database.php";
            include "User.php";
            ini_set('display_errors',"1");
            $db = new Database();

            $list = $db->getAvailablePlayers();

            foreach ($list as $item)
            {
                echo "<option value = '" . $item->getID() . "'>" . $item->getUserName() . "</option>";
            }
            ?>
            </select>
        </div>


        <button type="submit" class="btn btn-primary">Create game!</button>
    </form>


</div> <!-- /container -->


<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>



