<?php

ini_set('display_errors',"1");
session_start();
include "Database.php";
include "User.php";
include "Game.php";

//check to see if the session is set, if not the redirect them back to the
//login page. they should not be able to access this page unless they are logged in
//or else it will break the game since it requires session variables such as username to
//populate the screen.

//if the session variable is NOT set, then send them back
if( isset($_SESSION["userName"]) <> 1 )
{
    header('Location: ./index.phtml');
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">


    <title>Clue-less!</title>


    <!-- Bootstrap core CSS -->
    <link href="./css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="./css/grid.css" rel="stylesheet">
    <script src="./js/bootstrap.js"> </script>
    <script src="./js/bootstrap.js"> </script>

</head>

<body>
<div class="container">

    <!-- <h1>this is the game screen</h1>  -->
    <?php
        $db = new Database();
        $gameName = $db->getGameName($_GET['id']);

        echo "<h1>Welcome to Game: " . $gameName . ", " . $_SESSION["userName"] . "!</h1>";

        echo"<h3>People playing the game: </h3>";


        echo "<table class='table'>";
          echo "<thead>";

            echo "<tr>";
              echo "<th scope='col'>Play Order</th>";
              echo "<th scope='col'>Username</th>";
              echo "<th scope='col'>First Name</th>";
              echo "<th scope='col'>Character</th>";
              echo "<th scope='col'>Turn</th>";
              echo "<th scope='col'>Player Status</th>";
            echo "</tr>";
          echo "</thead>";
          echo "<tbody>";

          $list = $db->getPlayersFromGame($_GET['id']);

;

          $i = '';
          $i = 0;
          foreach ($list as $user)
          {
            echo "<tr>";
                echo "<th scope='row'>" . $user['characterNumber'] . "</th>";
                echo "<td>" . $user['userName'] . "</td>";
                echo "<td>" . $user['firstName'] . "</td>";
                //call the get character name here and set it
                echo "<td>" . $db->getSuspectCard($user['characterNumber']) . "</td>";

                if($user['isTurn'] == 1)
                {
                    echo "<td>yes</td>";
                }
                else
                {
                    echo "<td></td>";
                }
                //Todo create a col to indicate game winner
                if($db->isGameOver($db->getPlayersGameID($user['id'])) == true)
                {
                    if( $user['isEliminated'] == false)
                    {
                        echo "<td>winner</td>";
                    }
                    else{
                        // Indicate that the rest of the players are..
                        echo "<td>loser</td>";
                    }
                }
                else
                {
                    // When game is not yet over, a player can be eliminated by making a wrong accusation
                    // This is to indicate that
                    if( $user['isEliminated'] == true)
                    {
                        echo "<td>loser</td>";
                    }
                    else
                    {
                        echo "<td>active</td>";
                    }
                }

                echo "</tr>";

                $i++;
          }


          echo "</tbody>";
        echo "</table>";
        ?>

    <?php

    //todo: check to see if the users has been assigned a character or weapon, need to set this before

    //todo: call function to determine what moves the user can make
    //todo: send back results in a table.
    //todo: loop through result set and make a dropdown with the availbale moves. (needs to be in a form)
    //todo: after the user selects an option, they will need to click the submit button
    //todo: in the php file, validate that noone is currently in that spot. if so - handle the failure,
    //todo: if valid, process the payload and then redirect them to the gameboard.
    ?>

    <?php if($_SESSION["id"] == $db->getCurrentPlayer($_GET['id'])){ ?>


    <div class="container">


        <!-- TODO; send this to a page to call a function to validate and update the DB for the user's movement -->

        <hr/>


        <form action="playerMoves.php" method="POST">
            <div class="form-check form-check-inline">
                <label class="form-check-label" for="inlineRadio1">Where would you like to move?:</label>
            </div>
            <div class="form-check form-check-inline">
                <select class="form-control" id="exampleFormControlSelect1" name="move">
                <?php
                //get the current position of the player to determine where they can move on the board
                $currentPosition = $db->getPlayersBoardPosition($_SESSION["id"], $_GET['id']);
                //Todo: Add a condition to prevent player move if the game is over
                //Todo: Add a condidtion to prevent player move if player is eliminated
                //pass the current position into the method to get back a list of rows the player can move to
                //echo "<pre>";
                //print_r($currentPosition['roomName']);
                //echo "<pre>";

                if( $currentPosition['roomName'] == 'Study' ||
                    $currentPosition['roomName'] == 'Hall' ||
                    $currentPosition['roomName'] == 'Lounge' ||
                    $currentPosition['roomName'] == 'Dining Room' ||
                    $currentPosition['roomName'] == 'Kitchen' ||
                    $currentPosition['roomName'] == 'Ballroom' ||
                    $currentPosition['roomName'] == 'Conservatory' ||
                    $currentPosition['roomName'] == 'Library' ||
                    $currentPosition['roomName'] == 'Billard Room')
                {
                    //they player is currently in a room
                    $moves = $db->getAvailableMovesIfRoom($currentPosition['rowNumber'],$currentPosition['columnNumber']);

                    foreach ($moves as $move)
                    {
                        //get the text name of the position from the game map
                        $name = $db->getCellName($move,$_GET['id'] );
                        //set value of the select option to the 2 digit number and the text to the room/hall
                        echo "<option value='". $move . "'>Move to " . $name . "</option>";


                    }

                }
                else
                {
                    //they player is currently in a hallway
                    $moves = $db->getAvailableMovesIfHallway($currentPosition['rowNumber'],$currentPosition['columnNumber']);
                    foreach ($moves as $move)
                    {
                        //get the text name of the position from the game map
                        $name = $db->getCellName($move,$_GET['id'] );
                        //set value of the select option to the 2 digit number and the text to the room/hall
                        echo "<option value='". $move . "'>Move to " . $name . "</option>";


                    }
                }


                ?>
                </select>
            </div>
            <br />
            <div class="form-check form-check-inline">
                <label class="form-check-label" for="inlineRadio1">Would you like to make a suggestion(you can only make a suggestion for the room you move to)?:</label>
            </div>
            <div class="form-check form-check-inline">
                <select class="form-control" id="exampleFormControlSelect1" name="suspect">
                    <option value="1">Colonel Mustard</option>
                    <option value="2">Miss Scarlet</option>
                    <option value="3">Professor Plum</option>
                    <option value="4">Mr. Green</option>
                    <option value="5">Mrs. White</option>
                    <option value="6">Mrs. Peacock</option>
                </select>
            </div>
            <div class="form-check form-check-inline">
                <select class="form-control" id="exampleFormControlSelect1" name="weapon">
                    <option value="1">Rope</option>
                    <option value="2">Lead Pipe</option>
                    <option value="3">Knife</option>
                    <option value="4">Wrench</option>
                    <option value="5">Candlestick</option>
                    <option value="6">Revolver</option>
                </select>
            </div>
            <div class="form-check form-check-inline">
                <button name="submit" type="submit" class="btn btn-primary mb-2">Submit</button>
            </div>
        </form>

        <!-- TODO; send this to a page to validate user accusation -->
        <form action="playerMakesAccusation.php" method="POST">
            <div class="form-check form-check-inline">
                <label class="form-check-label" for="inlineRadio1">Would you like to make an accusation(you can only make an accusation when it's your turn)?:</label>
            </div>
            <div class="form-check form-check-inline">
                <select class="form-control" id="exampleFormControlSelect1" name="suspect">
                    <option value="Colonel Mustard">Colonel Mustard</option>
                    <option value="Miss Scarlet">Miss Scarlet</option>
                    <option value="Professor Plum">Professor Plum</option>
                    <option value="Mr. Green">Mr. Green</option>
                    <option value="Mrs. White">Mrs. White</option>
                    <option value="Mrs. Peacock">Mrs. Peacock</option>
                </select>
            </div>
            <div class="form-check form-check-inline">
                <select class="form-control" id="exampleFormControlSelect1" name="weapon">
                    <option value="Rope">Rope</option>
                    <option value="Lead Pipe">Lead Pipe</option>
                    <option value="Knife">Knife</option>
                    <option value="Wrench">Wrench</option>
                    <option value="Candlestick">Candlestick</option>
                    <option value="Revolver">Revolver</option>
                </select>
            </div>
            <div class="form-check form-check-inline">
                <select class="form-control" id="exampleFormControlSelect1" name="room">
                    <option value="Study">Study</option>
                    <option value="Hall">Hall</option>
                    <option value="Lounge">Lounge</option>
                    <option value="Dinning Room">Dinning Room</option>
                    <option value="Kitchen">Kitchen</option>
                    <option value="Ballroom">Ballroom</option>
                    <option value="Conservatory">Conservatory</option>
                    <option value="Library">Library</option>
                    <option value="Billard Room">Billard Room</option>
                </select>
            </div>
            <div class="form-check form-check-inline">
                <button name="submitAccusation" type="submit" class="btn btn-primary mb-2">Submit</button>
            </div>
        </form>
        <?php } ?>

        <hr>


        <?php

        $db = new Database();



        //this for loop with generate the game board
        $row = '';
        $column = '';



        for($row=1; $row<=5; $row++)
        {
            //start the row
            echo "<div class='row'>";

            //build the table by row,
            for($column = 1; $column <=5; $column++)
            {
                //account for row 2 and 4 that only have 3 columns (1,3,5)
                if($row == 2 || $row == 4)
                {
                    //increase the column numbers 1, 3, 5
                    if($column == 2 || $column == 4)
                    {
                        $rowObj = $db->getRowItems($_GET['id'],$row, ($column + 1));
                    }
                    else
                    {
                        $rowObj = $db->getRowItems($_GET['id'],$row, $column);
                    }
                }

                $rowObj = $db->getRowItems($_GET['id'],$row, $column);

                //this is where you want to assemble the table

                //change the color of the tile if it is a hallway

                if(strpos($rowObj["roomName"], 'hallway') !== false)
                {
                    //echo "<div class='col-2' style='background: white; border: none'></div>";
                    echo "<div class='col-2' style='background: #adb5bd'>" . $rowObj["roomName"];
                }

                else
                {
                    if(isset($rowObj["roomName"]))
                    {
                        echo "<div class='col-2'>" . $rowObj["roomName"];
                    }
                    else
                    {
                        //echo "<div class='col-2'>" . $rowObj["roomName"];
                        //echo "<div class='col-2'>" . "IS NOT SET";
                        echo "<div class='col-2' style='background: white'>";
                    }

                }
                //echo "<div class='col-2'>" . $rowObj["roomName"];
                    echo "<div class='row'>";
                    //display whether there is someone in the room/hallway
                    if($rowObj['occupant'] <> null)
                    {
                        //get the username & character name of the person in that square
                        //TODO add the username of the user that is the character
                        $suspectName = $db->getSuspectCard($rowObj['occupant']);
                        echo "<div class='col-md-6'>" . $suspectName. "</div>";
                    }
                    echo "</div>";
                echo "</div>";

            }
            echo "</div>";
        }

        ?>
        <!-- this will need to be generated dynamically by PHP-->
        <!--<div class="row">
            <div class="col-2">Library
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Billiard Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Dining Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: white; border: none"></div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: white; border: none"></div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-2">Library
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Billiard Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Dining Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: white; border: none"></div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: white; border: none"></div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-2">Conservatory
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Ballroom
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Kitchen
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div>
        -->
    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

