<?php

session_start();
include "Database.php";
include "User.php";
include "Game.php";


//check to see if the session is set, if not the redirect them back to the
//login page. they should not be able to access this page unless they are logged in
//or else it will break the game since it requires session variables such as username to
//populate the screen.

//if the session variable is NOT set, then send them back
if( isset($_SESSION["userName"]) <> 1 )
{
    header('Location: ./index.phtml');
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">


    <title>Clue-less!</title>


    <!-- Bootstrap core CSS -->
    <link href="./css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="./css/grid.css" rel="stylesheet">
    <script src="./js/bootstrap.js"> </script>
    <script src="./js/bootstrap.js"> </script>

</head>

<body>
<div class="container">

    <h1>Welcome, <?php echo $_SESSION["userName"] . "!"; ?> <br/ >Here is the grid system to use for game</h1>
    <p class="lead">Basic grid layout to use for game board.</p>

    <h3>Available Players</h3>
    <p>Players that are not currently assigned to a game</p>

    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">User Name</th>
            <th scope="col">First name</th>
            <th scope="col">Last Name</th>

        </tr>
        </thead>
        <tbody>
        <?php

        ini_set('display_errors',"1");
        $db = new Database();

        //returns a list of available players
        $list = $db->getAvailablePlayers();



        $i = 0;
        foreach ($list as $item)
        {
            //echo "<li>" . $item->getUserName() . "</li>";
            $i++;

            echo "<tr>";
            echo "<th>" . $item->getUserName() . "</th>";
            echo "<td>" . $item->getFirstName() . "</td>";
            echo "<td>" . $item->getLastName() . "</td>";

            echo "</tr>";

        $i++;
        }

        ?>
        </tbody>
    </table>

    <h3>Current Games</h3>
    <h5>These are the current games in progress <a class="btn btn-success" href="./createGame.phtml" role="button">Create Game</a></h5>
    <p>NOTE: if you join a game, it will unassign you from your current game</p>
    <table class="table table-striped">
        <thead>
        <tr>
            <th scope="col">Game #</th>
            <th scope="col"># players</th>
            <th scope="col">Action</th>
        </tr>
        </thead>
        <tbody>
        <?php
        $db = new Database();

        //returns a list of available players
        $list = $db->getCurrentGames($_SESSION["id"]);



        //$i = 0;
        foreach ($list as $item)
        {

            $id = $item->getID();
            $numPlayers = $db->getPlayersPerGame($id);


            echo "<tr>";
                echo "<th>" . $item->getName(). "</th>";
                echo "<td>" . "$numPlayers out of 6" . "</td>";


            $playersGameID = $db->getPlayersGameID($_SESSION["id"]);


            /*
            if($numPlayers < 6 && (!($playersGameID == $item->getID())))
            {
                echo "<td><a class='btn btn-outline-primary' href='joinGame.phtml?id=".$item->getID()."'>" . "Join Game" . "</a></td>";
            }
            */

            if($playersGameID == $item->getID())
            {
                //if the player is currently in that game, then show a yellow "enter game" button that takes them
                //to the game_board page for that specific game

                //TODO setup the game_board page to take in a query string to dynamically diplay the game's values
                //echo "<td><a class='btn btn-outline-primary' href='game_board.phtml?id=".$item->getID()."'>" . "Join Game" . "</a></td>";
                echo "<td><a class='btn btn-outline-success' href='game_board.phtml?id=".$item->getID()."'>" . "Go to Game" . "</a></td>";

            }
            /*
            else
            {
                echo "<td><a class='btn btn-outline-danger disabled' href='joinGame.phtml?id=".$item->getID()."'>" . "Game is Full" . "</a></td>";
            }
            */



            echo "</tr>";

            //$i++;
        }

        ?>
        </tbody>
    </table>

    <div class="card" style="width: 18rem;">
        <div class="card-body">
            <h5 class="card-title">Game Rules</h5>
            <h6 class="card-subtitle mb-2 text-muted">Movement Rules</h6>
            <p class="card-text">Quick overview of movement rules</p>
            <a href="move_rules.phtml" class="card-link">Rules Link</a>
        </div>
    </div>

    <hr>

    <div class="container">

        <!-- one of these will show up dynamically depending if you are in a room or a hallway PHP-->
        <!--<div class="row">
            <button class="col-4">Move to Hallway</button>
            <button class="col-4">Take Secret Passage</button>
            <button class="col-4">Move to Hall</button>
        </div>
        -->



        <!-- one of these will show up dynamically depending if you are in a room or a halwayby PHP-->
        <!--<div class="row">
            <button class="col-4">Move to Study</button>
            <button class="col-4">Move to Hallway</button>
            <button class="col-4">Move to Hall</button>
        </div>-->

        <hr>

    <!-- this will need to be generated dynamically by PHP-->
        <!--<div class="row">
            <div class="col-2">Library
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Billiard Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Dining Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div> -->
    <!--<div class="row">
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2" style="background: white; border: none"></div>
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2" style="background: white; border: none"></div>
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
    </div> -->

    <!--<div class="row">
        <div class="col-2">Library
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2">Billiard Room
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2">Dining Room
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2" style="background: white; border: none"></div>
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2" style="background: white; border: none"></div>
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-2">Conservatory
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2">Ballroom
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2" style="background: #adb5bd">Hallway
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
        <div class="col-2">Kitchen
            <div class="row">
                <div class="col-md-6">player</div>
            </div>
        </div>
    </div>-->
</div> <!-- /container -->

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

