<?php

session_start();
include "Database.php";
include "User.php";
include "Game.php";

ini_set('display_errors',"1");
$db = new Database();

//check to see if the session is set, if not the redirect them back to the
//login page. they should not be able to access this page unless they are logged in
//or else it will break the game since it requires session variables such as username to
//populate the screen.

//if the session variable is NOT set, then send them back
if( isset($_SESSION["userName"]) <> 1 )
{
    header('Location: ./index.phtml');
}

//get the username, or better yet get the user ID
$_SESSION["userName"];


//get the query string for the game that you wnat to add the player to
$_GET['id'];


//see how many players are in that game

//if there are less than 6 then add the player to the game

//call the DB object to add the user to the game (parameters need to be the game ID and the player ID)


//TODO get the game that the player is trying to join

//TODO find out which characters haven't been assigned uet

//todo assign character


$db->addPlayerToGame($_SESSION["id"], $_GET['id']);


//TODO: should this go to the direct game page?
header('Location: ./home.phtml');

