<?php

session_start();
include "Database.php";
include "User.php";
include "Game.php";


//check to see if the session is set, if not the redirect them back to the
//login page. they should not be able to access this page unless they are logged in
//or else it will break the game since it requires session variables such as username to
//populate the screen.

//if the session variable is NOT set, then send them back
if( isset($_SESSION["userName"]) <> 1 )
{
    header('Location: ./index.phtml');
}

?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">


    <title>Clue-less!</title>


    <!-- Bootstrap core CSS -->
    <link href="./css/bootstrap.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="./css/grid.css" rel="stylesheet">
    <script src="./js/bootstrap.js"> </script>
    <script src="./js/bootstrap.js"> </script>

</head>

<body>

<div class="container">
    <h3>Movement Rules</h3>

    <h4>If you are in a room, you may do one of the following</h4>
    <ul>
        <li>Move through one of the doors to the hallway (if it is not blocked).</li>
        <li>Take a secret passage to a diagonally opposite room (if there is one) and make a suggestion.</li>
        <li>If you were moved to the room by another player making a suggestion, you may, if you wish, stay in that room and make a suggestion. Otherwise you may move through a doorway or take a secret passage as described above.</li>
    </ul>

    <h4>If you are in a hallway, you must do the following</h4>
    <ul>
        <li>Move to one of the two rooms accessible from that hallway and make a suggestion.</li>
    </ul>

    <hr>
</div>

    <div class="container">

        <!-- one of these will show up dynamically depending if you are in a room or a hallway PHP-->
        <!--<div class="row">
            <button class="col-4">Move to Hallway</button>
            <button class="col-4">Take Secret Passage</button>
            <button class="col-4">Move to Hall</button>
        </div>
        -->



        <!-- one of these will show up dynamically depending if you are in a room or a halwayby PHP-->
        <!--<div class="row">
            <button class="col-4">Move to Study</button>
            <button class="col-4">Move to Hallway</button>
            <button class="col-4">Move to Hall</button>
        </div>-->

        <hr>

        <!-- this will need to be generated dynamically by PHP-->
        <!--<div class="row">
            <div class="col-2">Library
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Billiard Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Dining Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div> -->
        <!--<div class="row">
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: white; border: none"></div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: white; border: none"></div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div> -->

        <!--<div class="row">
            <div class="col-2">Library
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Billiard Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Dining Room
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: white; border: none"></div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: white; border: none"></div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-2">Conservatory
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Ballroom
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2" style="background: #adb5bd">Hallway
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
            <div class="col-2">Kitchen
                <div class="row">
                    <div class="col-md-6">player</div>
                </div>
            </div>
        </div>-->
    </div> <!-- /container -->

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

